#!/bin/bash

function createuser() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/user.scholarship.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/user.scholarship.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-user --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-user.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy user's CA cert to user's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/tlscacerts/ca.crt"

  # Copy user's CA cert to user's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.scholarship.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.scholarship.com/tlsca/tlsca.user.scholarship.com-cert.pem"

  # Copy user's CA cert to user's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/user.scholarship.com/ca"
  cp "${PWD}/organizations/fabric-ca/user/ca-cert.pem" "${PWD}/organizations/peerOrganizations/user.scholarship.com/ca/ca.user.scholarship.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-user --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-user --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-user --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-user --id.name useradmin --id.secret useradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls" --enrollment.profile tls --csr.hosts peer0.user.scholarship.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer0.user.scholarship.com/tls/server.key"

  echo "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/msp/config.yaml"

  echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls" --enrollment.profile tls --csr.hosts peer1.user.scholarship.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/user.scholarship.com/peers/peer1.user.scholarship.com/tls/server.key"


  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.scholarship.com/users/User1@user.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.scholarship.com/users/User1@user.scholarship.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://useradmin:useradminpw@localhost:7054 --caname ca-user -M "${PWD}/organizations/peerOrganizations/user.scholarship.com/users/Admin@user.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/user/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/user.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/user.scholarship.com/users/Admin@user.scholarship.com/msp/config.yaml"
}

function createuniversity() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/university.scholarship.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/university.scholarship.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-university --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-university.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-university.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-university.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-university.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/university.scholarship.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy university's CA cert to university's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/university.scholarship.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/university/ca-cert.pem" "${PWD}/organizations/peerOrganizations/university.scholarship.com/msp/tlscacerts/ca.crt"

  # Copy university's CA cert to university's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/university.scholarship.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/university/ca-cert.pem" "${PWD}/organizations/peerOrganizations/university.scholarship.com/tlsca/tlsca.university.scholarship.com-cert.pem"

  # Copy university's CA cert to university's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/university.scholarship.com/ca"
  cp "${PWD}/organizations/fabric-ca/university/ca-cert.pem" "${PWD}/organizations/peerOrganizations/university.scholarship.com/ca/ca.university.scholarship.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-university --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-university --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-university --id.name universityadmin --id.secret universityadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/university.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls" --enrollment.profile tls --csr.hosts peer0.university.scholarship.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/university.scholarship.com/peers/peer0.university.scholarship.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.scholarship.com/users/User1@university.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/university.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/university.scholarship.com/users/User1@university.scholarship.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://universityadmin:universityadminpw@localhost:8054 --caname ca-university -M "${PWD}/organizations/peerOrganizations/university.scholarship.com/users/Admin@university.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/university/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/university.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/university.scholarship.com/users/Admin@university.scholarship.com/msp/config.yaml"
}

function creategovAgency() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/govAgency.scholarship.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-govAgency --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-govAgency.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy govAgency's CA cert to govAgency's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/msp/tlscacerts/ca.crt"

  # Copy govAgency's CA cert to govAgency's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/tlsca/tlsca.govAgency.scholarship.com-cert.pem"

  # Copy govAgency's CA cert to govAgency's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/ca"
  cp "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem" "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/ca/ca.govAgency.scholarship.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-govAgency --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-govAgency --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-govAgency --id.name govAgencyadmin --id.secret govAgencyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls" --enrollment.profile tls --csr.hosts peer0.govAgency.scholarship.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/peers/peer0.govAgency.scholarship.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/users/User1@govAgency.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/users/User1@govAgency.scholarship.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://govAgencyadmin:govAgencyadminpw@localhost:11054 --caname ca-govAgency -M "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/users/Admin@govAgency.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/govAgency/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/govAgency.scholarship.com/users/Admin@govAgency.scholarship.com/msp/config.yaml"
}

function createscholarshipProvider() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/scholarshipProvider.scholarship.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-scholarshipProvider --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-scholarshipProvider.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-scholarshipProvider.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-scholarshipProvider.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-scholarshipProvider.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy scholarshipProvider's CA cert to scholarshipProvider's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem" "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/msp/tlscacerts/ca.crt"

  # Copy scholarshipProvider's CA cert to scholarshipProvider's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem" "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/tlsca/tlsca.scholarshipProvider.scholarship.com-cert.pem"

  # Copy scholarshipProvider's CA cert to scholarshipProvider's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/ca"
  cp "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem" "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/ca/ca.scholarshipProvider.scholarship.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-scholarshipProvider --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-scholarshipProvider --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-scholarshipProvider --id.name scholarshipProvideradmin --id.secret scholarshipProvideradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-scholarshipProvider -M "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-scholarshipProvider -M "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls" --enrollment.profile tls --csr.hosts peer0.scholarshipProvider.scholarship.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/peers/peer0.scholarshipProvider.scholarship.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-scholarshipProvider -M "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/users/User1@scholarshipProvider.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/users/User1@scholarshipProvider.scholarship.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://scholarshipProvideradmin:scholarshipProvideradminpw@localhost:10054 --caname ca-scholarshipProvider -M "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/users/Admin@scholarshipProvider.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/scholarshipProvider/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/scholarshipProvider.scholarship.com/users/Admin@scholarshipProvider.scholarship.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/scholarship.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/scholarship.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/scholarship.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/scholarship.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/scholarship.com/msp/tlscacerts/tlsca.scholarship.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/scholarship.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/scholarship.com/tlsca/tlsca.scholarship.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/scholarship.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls" --enrollment.profile tls --csr.hosts orderer.scholarship.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/scholarship.com/orderers/orderer.scholarship.com/msp/tlscacerts/tlsca.scholarship.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/scholarship.com/users/Admin@scholarship.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/scholarship.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/scholarship.com/users/Admin@scholarship.com/msp/config.yaml"
}



createuser
createuniversity
creategovAgency
createscholarshipProvider
createOrderer
